config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :leagues

end

app/models/age_class.rb
class AgeClass < ActiveRecord::Base
  has_many :players
  has_and_belongs_to_many :trainings

  validates :name, :from, :to, presence: true
  validate :from_cannot_be_greater_than_to


  private

  def from_cannot_be_greater_than_to
    return unless from and to
    errors.add(:from, "can't be greater than to") unless from < to
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, :dependent => :destroy

  validates :content, :user, :commentable, presence: true
end

app/models/game_event.rb
class GameEvent < ActiveRecord::Base
  belongs_to :team
  belongs_to :venue
  has_many :comments, as: :commentable, :dependent => :destroy
  has_many :players, through: :player_in_games

  validates :title, :start_time, :end_time, :team, :venue, presence: true
end

app/models/league.rb
class League < ActiveRecord::Base
  belongs_to :license
  has_many :teams

  validates :name, presence: true
end

app/models/license.rb
class License < ActiveRecord::Base
  has_many :players

  validates :name, presence: true
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :user
  belongs_to :license
  belongs_to :age_class
  has_and_belongs_to_many :training_events, counter_cache: true
  has_many :teams, through: :player_in_teams
  has_many :game_events, through: :player_in_games

  validates :user, :license, :age_class, presence: true
end

app/models/player_in_game.rb
class PlayerInGame < ActiveRecord::Base
  belongs_to :player
  belongs_to :game_event
end

app/models/player_in_team.rb
class PlayerInTeam < ActiveRecord::Base
  belongs_to :player
  belongs_to :team
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :players, through: :player_in_teams, counter_cache: true
  belongs_to :league
end

app/models/training.rb
class Training < ActiveRecord::Base
  has_many :training_events
  has_and_belongs_to_many :age_classes
end

app/models/training_event.rb
class TrainingEvent < ActiveRecord::Base
  has_one :training
  has_many :comments, as: :commentable, :dependent => :destroy
  has_and_belongs_to_many :player, counter_cache: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :invitable, :database_authenticatable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role
  has_one :player

  before_create :set_default_role

  private

  def set_default_role
    self.role ||= Role.find_by_name('registered')
  end

end

app/models/venue.rb
class Venue < ActiveRecord::Base
  has_many :game_events

  validates :name, :street, :plz, :city, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy]

  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.all
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
  end

  # GET /leagues/new
  def new
    @league = League.new
  end

  # GET /leagues/1/edit
  def edit
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(league_params)

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: 'League was successfully created.' }
        format.json { render :show, status: :created, location: @league }
      else
        format.html { render :new }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leagues/1
  # PATCH/PUT /leagues/1.json
  def update
    respond_to do |format|
      if @league.update(league_params)
        format.html { redirect_to @league, notice: 'League was successfully updated.' }
        format.json { render :show, status: :ok, location: @league }
      else
        format.html { render :edit }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league.destroy
    respond_to do |format|
      format.html { redirect_to leagues_url, notice: 'League was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_league
      @league = League.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def league_params
      params.require(:league).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta name="description" content="Internetpräsenz des DHSRC e.V."
    meta name="author" content="Lennart Kindermann"
    title
      | Starter Template for Bootstrap
    /! HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag 'https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js', 'https://oss.maxcdn.com/respond/1.4.2/respond.min.js'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
      .container
        .navbar-header
          button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar"
            span.sr-only
              | Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'Project name', '#', class: 'navbar-brand'
        #navbar.collapse.navbar-collapse
          ul.nav.navbar-nav
            li.active
              a href="#"
                | Home
            li
              a href="#about"
                | About
            li
              a href="#contact"
                | Contact
    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{ name == :error ? 'danger' : 'success' } alert-dismissable", role: 'alert' do
          button.close type="button" data-dismiss="alert"
            span aria-hidden="true"
              | &times;
            span.sr-only
              | Close
          = msg
      = yield

app/views/leagues/_form.html.slim
= form_for(@league, html: { class: 'form-horizontal', role: 'form' }) do |f|
  - if @league.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@league.errors.count,'error')} prohibited this league from being saved:"
      ul
        - @league.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :name, class: 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, class: 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'

app/views/leagues/edit.html.slim
.page-header
  = link_to leagues_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @league, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | league

= render 'form'

app/views/leagues/index.html.slim
.page-header
  = link_to new_league_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New League
  h1
    | Listing leagues

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
          | Liga
        th
        th
        th
    tbody
      - @leagues.each do | league |
        tr
          td
            = league.name
          td
            = link_to 'Show', league
          td
            = link_to 'Edit', edit_league_path(league) 
          td
            = link_to 'Destroy', league, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/leagues/new.html.slim
.page-header
  = link_to leagues_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | league

= render 'form'

app/views/leagues/show.html.slim
.page-header
  = link_to leagues_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_league_path(@league), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show league
dl.dl-horizontal
  dt
    | Liga
  dd
    = @league.name